# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-16 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='numChoices',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='question',
            name='tema',
            field=models.CharField(default='Vacío', max_length=200),
        ),
    ]
