# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-14 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200514_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='question_text',
            field=models.CharField(max_length=200),
        ),
    ]
