# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-15 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200514_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='question',
        ),
        migrations.AddField(
            model_name='choice',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='numChoices',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='question',
            name='tema',
            field=models.CharField(default='nada', max_length=200),
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
